### PR TITLE
Feat/Multiple Designed Pages

### PR DESCRIPTION
**Pull request by SpottedYodeler2**
## Overview
Designed the following pages:
- Edit Profile Page
- Home Page (Listings Page)
- Product Page 
- Create New Listing Page
- Edit Product Page

Handled the following cases:
- User have no profile and/or cover picture
- Product have to picture

### Edit Profile Page
image
### Home Page (Listings Page)
image
- Search feature working properly
### Product Page 
image
### Create New Listing Page
image
### Edit Product Page
image

### CODE REVIEW

**Review by chaaals — APPROVED** [review]
lsm (lupet so much)

**Review by am-cid — CHANGES_REQUESTED** [review]
thank you for this. I will fully test this tomorrow but from my initial testing and just looking at the pictures, here are some few things I noticed:
- edit profile has the option to remove picture, but nothing on the cover. I put `remove_cover` field in profile's form in `forms.py` for that reason, you can use that.
- edit product does not have the option to remove picture like the edit profile page. I also put `remove_picture` field in listing's form.
- when I (user `asdf`) go to the profile of someone else, I can see the edit profile button and when I click it, it redirects to my profile. Remove edit profile button if the current profile is not the mine

**Comment by SpottedYodeler2** [comment]
Hi @am-cid @chaaals! Pacheck nalang recent comits thanks

## Overview
New:
- Confirm Delete Modal
- Confirm Log Out Modal (Redirect to welcom page on logout )
- Add Profile Cover Photo

Fixed:
- Remove picture for product
- Remove cover page feature 
- Edit profile available on other users

## Screenshots
### Confirm Delete Page
image
### Confirm Log Out Modal 
image
### Add Profile Cover Photo
image



### I need help in fixing these pala:
- Not able to Register when there are spaces sa username
- Remove picture for product not funsctioning properly

**Comment by am-cid** [comment]
Initial just looking at code and pics, lgtm. I'll test tom
> ### I need help in fixing these pala:
> - Not able to Register when there are spaces sa username
> - Remove picture for product not funsctioning properly
- spaces in username are not allowed so that's intended behavior
- ill help debug that tomorrow

**Comment by am-cid** [comment]
misclick

**Review by am-cid — APPROVED** [review]
done with requested change. remove picture on listing now properly removes it.

**Pull request merged**
